import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);

  const signerAddress = process.env.REWARD_SIGNER_ADDRESS || deployer.address;
  const baseURI = process.env.BADGE_BASE_URI || "https://quiz.example.com/badges/";

  // Deploy QuizToken
  const QuizTokenFactory = await ethers.getContractFactory("QuizToken");
  const quizToken = await QuizTokenFactory.deploy(signerAddress);
  await quizToken.waitForDeployment();
  const tokenAddress = await quizToken.getAddress();
  console.log("QuizToken deployed to:", tokenAddress);

  // Deploy QuizBadgeNFT
  const BadgeFactory = await ethers.getContractFactory("QuizBadgeNFT");
  const badge = await BadgeFactory.deploy(signerAddress, baseURI);
  await badge.waitForDeployment();
  const badgeAddress = await badge.getAddress();
  console.log("QuizBadgeNFT deployed to:", badgeAddress);

  // Write addresses to lib/contracts/addresses.ts
  const addressesContent = `// Auto-generated by deploy.ts — do not edit manually
export const QUIZ_TOKEN_ADDRESS = (process.env.NEXT_PUBLIC_QUIZ_TOKEN_ADDRESS || '${tokenAddress}') as \`0x\${string}\`;
export const QUIZ_BADGE_ADDRESS = (process.env.NEXT_PUBLIC_QUIZ_BADGE_ADDRESS || '${badgeAddress}') as \`0x\${string}\`;
`;
  const outDir = path.resolve(__dirname, "../../lib/contracts");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "addresses.ts"), addressesContent);
  console.log("Addresses written to lib/contracts/addresses.ts");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
