import * as fs from "fs";
import * as path from "path";

const ARTIFACTS_DIR = path.resolve(__dirname, "../artifacts/contracts");
const OUT_DIR = path.resolve(__dirname, "../../lib/contracts");

function extractABI(contractName: string): unknown[] {
  const artifactPath = path.join(
    ARTIFACTS_DIR,
    `${contractName}.sol`,
    `${contractName}.json`
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  return artifact.abi;
}

function writeABI(contractName: string, abi: unknown[]): void {
  const content = `// Auto-generated by sync-abi.ts — do not edit manually
export const ${contractName}ABI = ${JSON.stringify(abi, null, 2)} as const;
`;
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, `${contractName}ABI.ts`), content);
  console.log(`Wrote ${contractName}ABI.ts`);
}

function main(): void {
  for (const name of ["QuizToken", "QuizBadgeNFT"]) {
    const abi = extractABI(name);
    writeABI(name, abi);
  }
}

main();
