// Auto-generated by deploy.ts — do not edit manually
export const QUIZ_TOKEN_ADDRESS = (process.env.NEXT_PUBLIC_QUIZ_TOKEN_ADDRESS || '0x76444237b7d382703d20CFFF4Af19f429CFbdE33') as `0x${string}`;
export const QUIZ_BADGE_ADDRESS = (process.env.NEXT_PUBLIC_QUIZ_BADGE_ADDRESS || '0x6629cE07d7c4093ccb0a7bEdDDBe6cF41f9A93F9') as `0x${string}`;
